// Do not edit this file directly. It is generated by the Calljmp CLI.

/* eslint-disable */

interface CloudServiceContext {
  platform: Platform;
  serviceId: string | null;
  userId?: string;
  development: boolean;
}

export abstract class CloudService<E extends CloudServiceEnv = CloudServiceEnv> {
  private _context?: CloudServiceContext;
  private _env?: E;

  get context() {
    if (!this._context) {
      throw new Error("Context is only available after fetch");
    }
    return this._context;
  }

  get database() {
    if (!this._env) {
      throw new Error("Environment not set");
    }
    return this._env.db;
  }

  get buckets() {
    if (!this._env) {
      throw new Error("Environment not set");
    }
    return {
    };
  }

  get secrets() {
    if (!this._env) {
      throw new Error("Environment not set");
    }
    return {
    };
  }

  get variables() {
    if (!this._env) {
      throw new Error("Environment not set");
    }
    return {
    };
  }

  async fetch(request: Request, env?: E, executionCtx?: ExecutionContext) {
    this._env = env;
    this._context = {
      platform: Platform.Unknown,
      serviceId: null,
      userId: undefined,
      development: env?.DEVELOPMENT === true,
    };

    const { args } = CloudServiceArgs.tryFrom(request);
    if (args) {
      this._context.platform = args.platform;
      this._context.serviceId = args.serviceId;
      this._context.userId = args.userId;
    }

    return this.onRequest(request, env, executionCtx);
  }

  protected abstract onRequest(request: Request, env?: E, executionCtx?: ExecutionContext): Response | Promise<Response>;
}

export enum Platform {
  Unknown = 'unknown',
  Android = 'android',
  iOS = 'ios',
}

const CLOUD_SERVICE_ARGS_HEADER = 'X-Calljmp-Args';

class CloudServiceArgs {
  public readonly platform: Platform;
  public readonly serviceId: string;
  public readonly userId?: string;

  private constructor(data: Record<string, unknown>) {
    this.platform = data.platform as Platform || Platform.Unknown;
    this.serviceId = data.serviceId as string;
    this.userId = data.userId as string;
  }

  static from(args: any) {
    let value: string | null = null;

    if ('req' in args && 'header' in args.req && typeof args.req.header === 'function') {
      // Hono Context
      value = args.req.header(CLOUD_SERVICE_ARGS_HEADER);
    } else if ('header' in args && typeof args.header === 'function') {
      // Hono Request
      value = args.header(CLOUD_SERVICE_ARGS_HEADER);
    } else if (args instanceof Request) {
      value = args.headers.get(CLOUD_SERVICE_ARGS_HEADER);
    } else if (args && typeof args === 'object') {
      value = args[CLOUD_SERVICE_ARGS_HEADER];
    } else if (typeof args === 'string') {
      value = args;
    }

    if (!value) {
      throw new Error(`Unable to resolve arguments from ${args}`);
    }

    const json = JSON.parse(value);

    return new CloudServiceArgs(json);
  }

  static tryFrom(args: any) {
    try {
      const data = CloudServiceArgs.from(args);
      return {
        args: data,
        error: null,
      }
    } catch (error) {
      return {
        args: null,
        error: error as Error,
      }
    }
  }
}
