-- TABLE: posts
CREATE TABLE posts(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,content TEXT NOT NULL,author INTEGER NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(author)REFERENCES users(id)ON DELETE CASCADE ON UPDATE CASCADE);

-- TABLE: reactions
CREATE TABLE reactions(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,user_id INTEGER NOT NULL,type VARCHAR(50)NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(post_id)REFERENCES posts(id)ON DELETE CASCADE ON UPDATE CASCADE,FOREIGN KEY(user_id)REFERENCES users(id)ON DELETE CASCADE ON UPDATE CASCADE);
